hand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Controllers ---------------------------------------
  rail_to_base_controller: # Lift
    type: position_controllers/JointPositionController
    joint: rail_to_base
    pid: {p: 300.0, i: 0.01, d: 10.0}
  base_to_finger_1_1_position_controller:
    type: position_controllers/JointPositionController
    joint: base_to_finger_1_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_1_1_to_finger_1_2_position_controller:
    type: effort_controllers/JointEffortController 
    joint: finger_1_1_to_finger_1_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_1_2_to_finger_1_3_position_controller:
    type: effort_controllers/JointEffortController 
    joint: finger_1_2_to_finger_1_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  base_to_finger_2_1_position_controller:
    type: position_controllers/JointPositionController
    joint: base_to_finger_2_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_2_1_to_finger_2_2_position_controller:
    type: effort_controllers/JointEffortController 
    joint: finger_2_1_to_finger_2_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_2_2_to_finger_2_3_position_controller:
    type: effort_controllers/JointEffortController 
    joint: finger_2_2_to_finger_2_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  base_to_finger_3_2_position_controller:
    type: effort_controllers/JointEffortController 
    joint: base_to_finger_3_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_3_2_to_finger_3_3_position_controller:
    type: effort_controllers/JointEffortController 
    joint: finger_3_2_to_finger_3_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
